### ISSUE TITLE
Problems booting with more than one usb ssd connected

### ISSUE THREAD

**Issue by kc4pl** [libre-computer-project/libretech-flash-tool#1]
I have tried booting with 3 usb ssd's connected to a powered hub on my aml-s905x-cc.  1 drive is the actual operating system disk, the 2 others are for a simple software raid system (mdadm).  Everything worked fine when I initially booted into the single drive.  But after adding 2 more ssd's and configuring the raid system on the next reboot the flash tool often can not see the actual boot drive.  On a couple of full power off start ups flash tool might find the actual boot drive maybe 1 of 4 tries.

**Comment by dsx724** [comment]
Do you have them connected to a powered USB hub?

**Comment by kc4pl** [comment]
Do you have them connected to a powered USB hub?
