### ISSUE TITLE
This doesn't work at all on OS X...

### ISSUE THREAD

**Issue by spyderdyne** [libre-computer-project/libretech-flash-tool#2]
Cloned, cd into directory, and executing shell script. BASH is not an installed shell on Darwin, so using ZSH:

spyderdyne@starscream libretech-flash-tool % sudo ./lft.sh bl-flash 00~aml-s905x-cc /dev/disk9
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
./lft.sh: line 9: lib/traps.sh: No such file or directory

spyderdyne@starscream libretech-flash-tool % sudo ./lft.sh bl-flash 00~aml-s905x-cc disk9     
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
./lft.sh: line 9: lib/traps.sh: No such file or directory

spyderdyne@starscream libretech-flash-tool % ls
diff.sh		lft.sh		lib		readme.md

spyderdyne@starscream libretech-flash-tool % pwd
/Users/spyderdyne/Documents/Projects/Libre/libretech-flash-tool

spyderdyne@starscream libretech-flash-tool % ls lib 
block-dev.sh	bootloader.sh	dmi.sh		traps.sh
board.sh	distro.sh	toolkit.sh	wget.sh

**Comment by dsx724** [comment]
We don't support anything other than Linux as we do not have the bandwidth. This means we have not tested any BSD nor MacOS. There's currently no plans to support ZSH or Mac as we use too many bash facilities.

**Comment by spyderdyne** [comment]
Ok.

You don't appear to support your own images either, because n9ne of them
seem to be bookable on your hardware via SDCard. Obviously I wouldn't even
need to attempt using this "official" method of creat8ng a bootable SDCard
if any of the more sane methods (Balena or dd) resulted in a usable SBC.

Not much point in you guys going to all the trouble of designing the
product if it cannot be used at all due to lack of an operating system...

**Comment by dsx724** [comment]
Please see and use hub.libre.computer for guides on how to flash images. All of our images are CI'ed meaning that they run on physical boards before they're deployed to our S3. If an image does not work, it's likely a compatibility issue with peripheral (power, display) or user error during flashing. Without more information, we cannot help you. However, your generalization is incorrect.
